name: CI/CD

on:
  push:
    branches:
      - canary
    tags:
      - v*

  pull_request:
    branches:
      - canary

jobs:
  build:
    name: Build (${{ matrix.os-short }}-${{ matrix.platform }})
    runs-on: ${{ matrix.os }}

    # Strategy
    # or a.k.a variables for multiple platforms
    # https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstrategy
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macOS-latest
        platform:
          - any
          - cpuonly

        include:
          - os: ubuntu-latest # Ubuntu
            os-short: ubuntu
            python: python3
          - os: ubuntu-latest # Ubuntu & CPU
            platform: cpuonly
            setup-args: --cpu
          - os: windows-latest # Windows
            os-short: windows
            python: python
          - os: windows-latest # Windows & CPU
            platform: cpuonly
            setup-args: --cpu
          - os: macOS-latest # macOS
            os-short: macos
            python: python3
            setup-args: --cpu

        exclude:
          - os: macOS-latest
            platform: any

    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true

      - name: Use Python 3.7
        uses: actions/setup-python@v1
        if: runner.os != 'macOS'
        with:
          python-version: 3.7
          architecture: x64

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Use 7z
        if: matrix.os-short == 'macos'
        run: brew install p7zip

      - name: Use Yarn
        run: npm install -g yarn

      - name: Setup - Release Script
        working-directory: scripts
        run: |
          yarn install

      - name: Setup - DreamPower
        working-directory: scripts
        run: |
          ${{ matrix.python }} setup.py --debug --pip_no_cache_dir ${{ matrix.setup-args }}

      - name: Build
        working-directory: scripts
        run: |
          ${{ matrix.python }} build.py --debug

      - name: Release
        working-directory: scripts
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          GITHUB_SHA: ${{ github.sha }}
          GITHUB_REF: ${{ github.ref }}
          BUILD_OS: ${{ matrix.os-short }}
          BUILD_PLATFORM: ${{ matrix.platform }}
        run: |
          node release.js
